### PR TITLE
cts: include ADDITIONAL_LIBS in variables to CTS stage

### PR DESCRIPTION
**Pull request by oharboe**
Ideally we provide only the variables relevant for a stage to that stage. Is ADDITIONAL_LIBS relevant, other than for `make cts_issue`?

What about ADDITIONAL_LEFS?

This is not strictly necessary for the execution of this stage, but it is useful, otherwise .lib files for macros are not included in make cts_issue.

### CODE REVIEW

**Comment by oharboe** [comment]
@lpawelcz We'll need a `bazelisk build *_issue` target that creates a `_make` file which includes all variables for all stages. This will be used for make issue use-case.

**Comment by maliberty** [comment]
> This is not strictly necessary for the execution of this stage,

If your cts stage matches ORFS then the .lib are necessary for repair_timing.

**Comment by oharboe** [comment]
> > This is not strictly necessary for the execution of this stage,
> 
> If your cts stage matches ORFS then the .lib are necessary for repair_timing.

Why dont I get an error without the .lib files in CTS?

**Comment by maliberty** [comment]
sta will treat them as black boxes with no timing (as will proprietary tools).

**Comment by oharboe** [comment]
> sta will treat them as black boxes with no timing (as will proprietary tools).

how can I tell which stages use .lef and .def files?

**Comment by maliberty** [comment]
lef/def are needed just at floorplan and gds generation as they are stored in odb.  Liberty are not and are needed at any stage that does timing - it is simplest to assume all stages.

**Comment by oharboe** [comment]
> lef/def are needed just at floorplan and gds generation as they are stored in odb. Liberty are not and are needed at any stage that does timing - it is simplest to assume all stages.

Fixed.

**Pull request merged**
