### PR TITLE
Revert faster docker extract

### PR DESCRIPTION
**Pull request by oharboe**
@jeffng-or Please try this to see if it works:

```
$ cd bazel-orfs/
$ git fetch origin pull/121/head
$ git checkout FETCH_HEAD
$ bazel build tag_array_64x184_synth
```

### CODE REVIEW

**Comment by oharboe** [comment]
@tmichalak This is to restore hermiticity and avoid having docker installed as a dependency.

@hovind Correct?

**Comment by oharboe** [comment]
@hovind If I uninstall docker, I get this error, so there is a dependency on docker. So... not hermetic...

```
$ bazel build tag_array_64x184_synth
INFO: Repository _main~orfs_repositories~docker_orfs instantiated at:
  <builtin>: in <toplevel>
Repository rule docker_pkg defined at:
  /home/oyvind/bazel-orfs/docker.bzl:55:29: in <toplevel>
ERROR: An error occurred during the fetch of repository '_main~orfs_repositories~docker_orfs':
   Traceback (most recent call last):
        File "/home/oyvind/bazel-orfs/docker.bzl", line 24, column 13, in _impl
                fail("Failed to build {}:".format(repository_ctx.attr.image), build_result.stderr)
Error in fail: Failed to build docker.io/openroad/orfs:v3.0-1266-ge623a237: ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
ERROR: no such package '@@_main~orfs_repositories~docker_orfs//': Failed to build docker.io/openroad/orfs:v3.0-1266-ge623a237: ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
ERROR: /home/oyvind/bazel-orfs/BUILD:62:10: //:tag_array_64x184_synth depends on @@_main~orfs_repositories~docker_orfs//:asap7 in repository @@_main~orfs_repositories~docker_orfs which failed to fetch. no such package '@@_main~orfs_repositories~docker_orfs//': Failed to build docker.io/openroad/orfs:v3.0-1266-ge623a237: ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
ERROR: Analysis of target '//:tag_array_64x184_synth' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.845s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

**Comment by oharboe** [comment]
We want to have the podman-docker option and this would rely on docker specifically.

**Comment by jeffng-or** [comment]
@maliberty , @oharboe 

One downside to switching to podman-docker is that it interferes with doing OR/ORFS development since setup.sh expects to be able to unpack docker:

```
$ sudo ./setup.sh 
...
Selecting previously unselected package docker-buildx-plugin.
Preparing to unpack .../docker-buildx-plugin_0.16.2-1~ubuntu.22.04~jammy_amd64.deb ...
Unpacking docker-buildx-plugin (0.16.2-1~ubuntu.22.04~jammy) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a27.2.0-1~ubuntu.22.04~jammy_amd64.deb ...
Unpacking docker-ce-cli (5:27.2.0-1~ubuntu.22.04~jammy) ...
dpkg: error processing archive /var/cache/apt/archives/docker-ce-cli_5%3a27.2.0-1~ubuntu.22.04~jammy_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/docker', which is also in package podman-docker 3.4.4+ds1-1ubuntu1.22.04.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a27.2.0-1~ubuntu.22.04~jammy_amd64.deb ...
Unpacking docker-ce (5:27.2.0-1~ubuntu.22.04~jammy) ...
Errors were encountered while processing:
 /var/cache/apt/archives/docker-ce-cli_5%3a27.2.0-1~ubuntu.22.04~jammy_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

So, podman-docker should work on the CI worker machines since we're not doing development on them. But for anyone doing development, I'm not sure we can use the same machine.

**Comment by oharboe** [comment]
I see.

bazel-orfs will work with a correctly configured docker, like ./setup.sh is using.

podman-docker is simply an option for certain environments.... such as inside a github docker image(podman-docker not tested, but it one would think it has a good chance to work, not requiring root access).

docker can also run rootless, but it is a pain to configure.

**Pull request closed without merging**
