### PR TITLE
openroad: Combine canonicalization and synth actions into one step

### PR DESCRIPTION
**Pull request by hovind**
@oharboe FYI.
@mleonowicz what do you think about https://github.com/The-OpenROAD-Project/bazel-orfs/commit/c9861eb4fee927d2f8029734999ae3c1fdaaffc2 instead of adding multiple sources?

### CODE REVIEW

**Review by oharboe — CHANGES_REQUESTED** [review]
fix bazel lint

**Comment by mleonowicz** [comment]
@hovind 
I think it the `forwarded_names` approach looks good as well. I decided to go with multiple sources to be more explicit about the dependency graph and to avoid having to manually choose files that are to be passed to the `grt` stage (in a similar way we do not pass `congestion.rpt` file to the `grt` stage)

**Comment by hovind** [comment]
> @hovind I think it the `forwarded_names` approach looks good as well. I decided to go with multiple sources to be more explicit about the dependency graph and to avoid having to manually choose files that are to be passed to the `route` stage (in a similar way we do not pass `congestion.rpt` file to the `route` stage)

**Comment by hovind** [comment]
efer 

> @hovind I think it the `forwarded_names` approach looks good as well. I decided to go with multiple sources to be more explicit about the dependency graph and to avoid having to manually choose files that are to be passed to the `route` stage (in a similar way we do not pass `congestion.rpt` file to the `route` stage)

**Comment by hovind** [comment]
> @hovind I think it the `forwarded_names` approach looks good as well. I decided to go with multiple sources to be more explicit about the dependency graph and to avoid having to manually choose files that are to be passed to the `route` stage (in a similar way we do not pass `congestion.rpt` file to the `route` stage)

Great! I prefer adding a reusable mechanism (`forwarded_names`) to having to perform surgery like
```
        if step.stage == 'route':
            srcs.append(name_template.format(name, "cts"))
```
and
```
(previous_reports if stage == '5_2_route' else [])
```

**Pull request merged**
