### PR TITLE
bump to ORFS v3.0-1496-g20cf8faa

### PR DESCRIPTION
**Pull request by jeffng-or**
ORFS bump to v3.0-1496-g20cf8faa

### CODE REVIEW

**Comment by jeffng-or** [comment]
All ORFS versions after v3.0-1461-ge58a24fe fail in mpl with:

```
[ERROR MPL-0072] No partition solutions found.
```
Will investigate more

**Comment by oharboe** [comment]
@maliberty @jeffng-or Red Herring, it is just RTLMP_FLOW=0 that is broken.

**Comment by oharboe** [comment]
Trying fix https://github.com/The-OpenROAD-Project/bazel-orfs/pull/178

**Comment by jeffng-or** [comment]
> @maliberty @jeffng-or Red Herring, it is just RTLMP_FLOW=0 that is broken.

OK to proceed with merge then?

**Comment by oharboe** [comment]
This PR was merged as part of https://github.com/The-OpenROAD-Project/bazel-orfs/pull/178

**Pull request closed without merging**
